// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RonBNPspMUEbv253fGj-DBKXVCbhxOc',
    appId: '1:320437674855:web:73d329126aead5f2fd85c2',
    messagingSenderId: '320437674855',
    projectId: 'vroom-2a5f2',
    authDomain: 'vroom-2a5f2.firebaseapp.com',
    storageBucket: 'vroom-2a5f2.firebasestorage.app',
    measurementId: 'G-C8R90V9Z2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpQei8LWcKex4n8UBVCmaw-Dn4AuYokg',
    appId: '1:320437674855:android:ec7044dcebb2bedefd85c2',
    messagingSenderId: '320437674855',
    projectId: 'vroom-2a5f2',
    storageBucket: 'vroom-2a5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gdEiLdmKiHf_VgzffkVTiGzrxkgGSEk',
    appId: '1:320437674855:ios:ce05502c0089c562fd85c2',
    messagingSenderId: '320437674855',
    projectId: 'vroom-2a5f2',
    storageBucket: 'vroom-2a5f2.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gdEiLdmKiHf_VgzffkVTiGzrxkgGSEk',
    appId: '1:320437674855:ios:ce05502c0089c562fd85c2',
    messagingSenderId: '320437674855',
    projectId: 'vroom-2a5f2',
    storageBucket: 'vroom-2a5f2.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RonBNPspMUEbv253fGj-DBKXVCbhxOc',
    appId: '1:320437674855:web:14d9724ebc163bdafd85c2',
    messagingSenderId: '320437674855',
    projectId: 'vroom-2a5f2',
    authDomain: 'vroom-2a5f2.firebaseapp.com',
    storageBucket: 'vroom-2a5f2.firebasestorage.app',
    measurementId: 'G-P56BM3QGN9',
  );
}
